import { it, expect, vi, beforeEach } from 'vitest';
import { crearManejadorCita } from '../api/_lib/cita-http.js';
import { crearAlmacenMemoria } from '../api/_lib/almacen-memoria.js';
const C={notaria:{direccion:'Quito',horario:{dias:[1,2,3,4,5],abre:'08:00',cierra:'17:00',texto:'Lunes a viernes'},citas:{porHora:2,feriados:[]}},data:{tramites:[{id:'poder',nombre:'Poder',cat:'poderes',req:['Cédula'],tarifa:{tipo:'fija',valor:10}},{id:'revision',nombre:'Revisión',revision:true,req:[],tarifa:{tipo:'consultar'}}]},tarifas:{iva:0.15}};
let almacen, avisar, api;
const cuerpo={nombre:'Ana Pérez',celular:'0991234567',tramiteId:'poder',fecha:'2026-10-12',hora:'09:30',aceptaAviso:true,sitio:''};
const req=(b=cuerpo,ip='1')=>new Request('https://n.ec/api/cita',{method:'POST',headers:{'content-type':'application/json','x-forwarded-for':ip},body:JSON.stringify(b)});
beforeEach(()=>{almacen=crearAlmacenMemoria();avisar=vi.fn();api=crearManejadorCita({almacen,avisar,contenido:async()=>C,ahora:()=>new Date('2026-10-12T12:00:00Z')});});
it('GET entrega disponibilidad, trámites y no-store',async()=>{const r=await api.GET(new Request('https://n.ec/api/cita'));expect(r.headers.get('Cache-Control')).toBe('no-store');expect(await r.json()).toMatchObject({dias:expect.any(Array),tramites:[{id:'poder',nombre:'Poder',cat:'poderes'},{id:'revision',nombre:'Revisión'}]});});
it.each([{nombre:'A'},{nombre:'A'.repeat(81)},{celular:'123'},{celular:'593812345678'},{aceptaAviso:false},{tramiteId:'inventado'},{nota:'a'.repeat(201)},{fecha:'2026-02-30'},{hora:'25:00'}])('valida %j',async cambio=>{expect((await api.POST(req({...cuerpo,...cambio}))).status).toBe(400);});
it('campo trampa no guarda datos',async()=>{expect((await api.POST(req({...cuerpo,sitio:'robot'}))).status).toBe(201);expect(await almacen.conversaciones()).toEqual([]);expect(avisar).not.toHaveBeenCalled();});
it('confirma, registra consentimiento y contacto, avisa hoy y rechaza cita activa',async()=>{const r=await api.POST(req());expect(r.status).toBe(201);const {resumen}=await r.json();expect(resumen).toMatchObject({estado:'confirmada',subirDocumentos:false,codigo:expect.stringMatching(/^\d{4}$/)});const conv=await almacen.conversacionPorTelefono('form:593991234567');expect(conv).toMatchObject({consentimiento:true,nombre:'Ana Pérez',consentimientoAviso:expect.any(String)});expect((await almacen.solicitudesCita(conv.id))[0]).toMatchObject({contacto:'593991234567'});expect(avisar).toHaveBeenCalledWith(expect.stringContaining('(formulario)'));const repetida=await api.POST(req());expect(repetida.status).toBe(409);expect((await repetida.json()).error).toContain('ticket '+resumen.codigo);});
it('queda pendiente si requiere revisión; desconocido queda confirmado',async()=>{let r=await api.POST(req({...cuerpo,tramiteId:'revision',fecha:'2026-10-13'}));expect((await r.json()).resumen.estado).toBe('pendiente');expect(avisar).toHaveBeenCalledOnce();r=await api.POST(req({...cuerpo,celular:'0991234568',tramiteId:null,fecha:'2026-10-13'}));expect((await r.json()).resumen.estado).toBe('confirmada');expect(avisar).toHaveBeenCalledOnce();});
it('409 devuelve días renovados si se ocupó la hora',async()=>{await almacen.guardarAjuste('citas.porHora','1');await api.POST(req());const r=await api.POST(req({...cuerpo,celular:'0991234568',hora:'09:00'}));expect(r.status).toBe(409);const b=await r.json();expect(b.error).toBe('Esa hora acaba de ocuparse. Elige otra.');expect(b.dias[0].horas).not.toContain('09:30');});
it.each(['consultas','porIp','porCelular','porDia'])('limita %s con 429',async clave=>{const limites={consultas:120,porIp:5,porCelular:3,porDia:200,[clave]:0};const a=crearManejadorCita({almacen,contenido:async()=>C,limites,ahora:()=>new Date('2026-10-12T12:00:00Z')});expect((await (clave==='consultas'?a.GET(new Request('https://n.ec/api/cita')):a.POST(req()))).status).toBe(429);});

it("GET entrega los nombres de las categorías para agrupar la lista de trámites", async () => {
  const conCategorias = { ...C, data: { ...C.data, categorias: [{ id: "poderes", nombre: "Poderes", desc: "no hace falta" }] } };
  const a = crearManejadorCita({ almacen, contenido: async () => conCategorias, ahora: () => new Date("2026-10-12T12:00:00Z") });
  expect((await (await a.GET(new Request("https://n.ec/api/cita"))).json()).categorias).toEqual([{ id: "poderes", nombre: "Poderes" }]);
});
